pool:
  name: MySelfHostedPool

trigger:
  - main

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.0.102'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet restore WebApplication1/WebApplication1.sln
  displayName: 'Restore Dependencies'

- script: dotnet build WebApplication1/WebApplication1.sln --no-restore
  displayName: 'Build Solution'

- script: dotnet test WebApplication1/WebApplication1.Tests.csproj --no-build
  displayName: 'Run Tests'

- script: echo "Database access has already been done on April 14, 2023 by Landon Essex"
  displayName: 'Display DB Message'
